name: Add issues to Projects

on:
  issues:
    types:
      - opened
      - reopened
      - labeled

jobs:
  add-to-project-web:
    name: Add to Kcumen Web 2026 Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/kcumen/projects/6
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

  add-to-operations:
    name: Add to Kcumen Operations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/kcumen/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}